import {test,expect} from '@playwright/test';
import {PrivateKey,PublicKey,Signature,Hash,BufferUtils} from '@nimiq/core';
test('wallet signed connection and disconnect with injected test provider',async({page})=>{
 const key=PrivateKey.generate(),pub=PublicKey.derive(key),address=pub.toAddress().toUserFriendlyAddress();
 await page.exposeFunction('testSign',async(message:string)=>({publicKey:pub.toHex(),signature:Signature.create(key,pub,Hash.computeSha256(BufferUtils.fromUtf8(`\x16Nimiq Signed Message:\n${new TextEncoder().encode(message).length}${message}`))).toHex()}));
 await page.addInitScript(address=>{(window as any).nimiq={listAccounts:async()=>[address],sign:(message:string)=>(window as any).testSign(message)}},address);
 await page.goto('/');await page.getByRole('button',{name:'Connect',exact:true}).click();await page.getByRole('button',{name:'Connect Nimiq Pay',exact:true}).click();await expect(page.getByRole('heading',{name:'Make it yours.'})).toBeVisible();await page.getByLabel('Player name').fill('Wallet Knight');await page.getByRole('button',{name:'Save profile'}).click();await page.reload();await page.getByRole('button',{name:'Connected',exact:true}).click();await expect(page.getByRole('heading',{name:'You’re connected.'})).toBeVisible();await expect(page.locator('.address-box')).toContainText(address);await page.getByRole('button',{name:'Disconnect wallet'}).click();await expect(page.getByRole('button',{name:'Connect Nimiq Pay',exact:true})).toBeVisible();
});
test('missing native provider gives readable recoverable feedback',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Connect',exact:true}).click();await page.getByRole('button',{name:'Connect Nimiq Pay',exact:true}).click();await expect(page.getByRole('status')).toContainText('Open NimChess inside Nimiq Pay',{timeout:15000});await expect(page.getByRole('status')).toBeVisible();await expect(page.getByRole('button',{name:'Connect Nimiq Pay',exact:true})).toBeEnabled();await page.screenshot({path:'artifacts/wallet-feedback.png'});});
for(const width of [360,1280])test(`all tabs fit at ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await page.goto('/');for(const name of ['Play','Puzzles','Club','You']){await page.getByRole('button',{name,exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),name).toBeTruthy();await page.screenshot({path:`artifacts/${width}-${name}.png`,fullPage:true})}await page.getByRole('button',{name:'How to play & club guide'}).click();await expect(page.getByRole('heading',{name:'The goal',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close dialog',exact:true}).click();});
