import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:http';
import {Chess} from 'chess.js';
import {createApp,createDb,PUZZLES} from './app';
async function setup(){const dir=mkdtempSync(join(tmpdir(),'nimchess-release-'));const db=createDb(dir);const server=createServer(createApp({db}));await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;async function guest(){const r=await fetch(base+'/api/session');return r.headers.get('set-cookie')!.split(';')[0]}async function call(cookie:string,path:string,body?:unknown,method=body===undefined?'GET':'POST'){const r=await fetch(base+'/api'+path,{method,headers:{cookie,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json() as any}}return {db,guest,call,close:()=>{server.closeAllConnections();server.close();db.close();rmSync(dir,{recursive:true})}}}
test('all puzzle solutions are legal checkmates with distinct solutions',()=>{assert.equal(new Set(PUZZLES.map(p=>p.solution[0])).size,8);for(const p of PUZZLES){const c=new Chess(p.fen);for(const move of p.solution)c.move(move);assert.ok(c.isCheckmate(),p.title)}});
test('complete multiplayer PGN, history, reactions, draw and settlement idempotency',async()=>{const x=await setup();try{const a=await x.guest(),b=await x.guest(),outsider=await x.guest();const created=await x.call(a,'/matches',{minutes:5,increment:2,rated:true});const id=created.data.match.id;assert.equal((await x.call(b,`/matches/${id}/join`,{})).status,200);for(const [cookie,from,to] of [[a,'e2','e4'],[b,'e7','e5'],[a,'g1','f3'],[b,'b8','c6']])assert.equal((await x.call(cookie,`/matches/${id}/move`,{from,to})).status,200);assert.equal((await x.call(outsider,`/matches/${id}/reaction`,{emoji:'gg'})).status,403);assert.equal((await x.call(a,`/matches/${id}/reaction`,{emoji:'gg'})).status,200);await x.call(a,`/matches/${id}/draw`,{action:'offer'});const end=await x.call(b,`/matches/${id}/draw`,{action:'accept'});assert.equal(end.data.match.result,'1/2-1/2');for(let i=0;i<3;i++)await x.call(a,`/matches/${id}`);assert.equal((await x.call(a,'/session')).data.profile.games,1);const h=(await x.call(a,'/history')).data.matches[0];assert.ok(h.white.name);const c=new Chess();c.loadPgn(h.pgn);assert.equal(c.history().length,4);assert.equal(h.black.id,end.data.match.black.id);const rematch=await x.call(a,`/matches/${id}/rematch`,{});assert.equal((await x.call(b,`/matches/${rematch.data.match.id}/join`,{})).data.match.status,'active')}finally{x.close()}});
test('expired clock blocks move and invalid practice/profile inputs fail',async()=>{const x=await setup();try{const a=await x.guest(),b=await x.guest();const id=(await x.call(a,'/matches',{minutes:3,increment:0,rated:true})).data.match.id;await x.call(b,`/matches/${id}/join`,{});const row=x.db.prepare('SELECT data FROM matches WHERE id=?').get(id) as {data:string};const m=JSON.parse(row.data);m.lastMoveAt=Date.now()-200000;x.db.prepare('UPDATE matches SET data=? WHERE id=?').run(JSON.stringify(m),id);assert.equal((await x.call(a,`/matches/${id}/move`,{from:'e2',to:'e4'})).status,409);assert.equal((await x.call(a,`/matches/${id}`)).data.match.reason,'timeout');assert.equal((await x.call(a,'/practice',{pgn:'not chess',mode:'bot'})).status,422);assert.equal((await x.call(a,'/profile',{rating:9999},'PATCH')).status,400);assert.equal((await x.call(a,'/profile',{name:'Tester',avatar:'nova',theme:'sand'},'PATCH')).status,200)}finally{x.close()}});
