import {useCallback,useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,Check,ChevronRight,Clock,Crown,Download,Flame,Gamepad2,Heart,Lightbulb,Link,LoaderCircle,Palette,Play,Plus,Settings,ShieldCheck,Shuffle,Sparkles,Swords,Target,Trophy,User,Users,Wallet,X,Zap} from 'lucide-react';
import {Chess} from 'chess.js';
import type {Match,Profile,Puzzle} from '../shared/types';
import {api,download,share} from './api';
import {Avatar,avatars,facts,Modal,rankFor,ranks} from './components';
import ChessBoard from './game/ChessBoard';
import MatchView from './game/MatchView';
type Tab='play'|'puzzles'|'club'|'profile';
type Game={mode:'bot'|'local'|'online';match?:Match;difficulty?:'easy'|'medium'|'hard';minutes:number;increment:number};
export default function App(){
 const [tab,setTab]=useState<Tab>('play'),[profile,setProfile]=useState<Profile|null>(null),[error,setError]=useState(''),[toast,setToast]=useState(''),[game,setGame]=useState<Game|null>(()=>{try{const g=JSON.parse(sessionStorage.getItem('nimchess.active')||'null');return g&&['bot','local'].includes(g.mode)&&[3,5,10].includes(g.minutes)?g:null}catch{return null}}),[modal,setModal]=useState<'setup'|'wallet'|'settings'|'help'|null>(null),[setup,setSetup]=useState<'bot'|'local'|'online'>('bot'),[difficulty,setDifficulty]=useState<'easy'|'medium'|'hard'>('medium'),[minutes,setMinutes]=useState(5),[increment,setIncrement]=useState(0),[busy,setBusy]=useState(false),[fact,setFact]=useState(0),[history,setHistory]=useState<Match[]>([]),[leaders,setLeaders]=useState<Profile[]>([]),[puzzles,setPuzzles]=useState<Puzzle[]>([]),[activePuzzle,setActivePuzzle]=useState<Puzzle|null>(null),[replay,setReplay]=useState<Match|null>(null),[tipTarget,setTipTarget]=useState<{name:string;address:string}|null>(null);
 useEffect(()=>{try{if(game&&game.mode!=='online')sessionStorage.setItem('nimchess.active',JSON.stringify(game));else sessionStorage.removeItem('nimchess.active')}catch{}},[game]);
 const notify=useCallback((text:string)=>setToast(text),[]);
 const refresh=useCallback(async()=>{const result=await api<{profile:Profile}>('/session');setProfile(result.profile);return result.profile},[]);
 useEffect(()=>{refresh().then(async()=>{const id=new URLSearchParams(location.search).get('match');if(id){const {match}=await api<{match:Match}>('/matches/'+encodeURIComponent(id));setGame({mode:'online',match,minutes:5,increment:match.increment/1000})}}).catch(e=>setError(e.message));api<{puzzles:Puzzle[]}>('/puzzles').then(v=>setPuzzles(v.puzzles)).catch(()=>{});},[refresh]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer)},[toast]);
 useEffect(()=>{if(tab==='profile')api<{matches:Match[]}>('/history').then(d=>setHistory(d.matches)).catch(e=>notify(e.message));if(tab==='club')api<{profiles:Profile[]}>('/leaderboard').then(d=>setLeaders(d.profiles)).catch(e=>notify(e.message));},[tab,notify]);
 useEffect(()=>{document.documentElement.dataset.theme=profile?.theme||'sage'},[profile?.theme]);
 async function start(){setBusy(true);try{sessionStorage.removeItem('nimchess.position');if(setup==='online'){const {match}=await api<{match:Match}>('/matches','POST',{minutes,increment,rated:true});setGame({mode:'online',match,minutes,increment});historyReplace(match.id)}else setGame({mode:setup,difficulty,minutes,increment});setModal(null)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 function historyReplace(id?:string){window.history.replaceState(null,'',id?'?match='+id:location.pathname)}
 function exitGame(){sessionStorage.removeItem('nimchess.position');setGame(null);historyReplace();refresh().catch(()=>{})}
 async function savePractice(pgn:string,result:string){try{await api('/practice','POST',{pgn,result,mode:game?.mode||'bot'});await refresh()}catch(e){notify((e as Error).message)}}
 async function saveProfile(data:Partial<Profile>){const {profile:p}=await api<{profile:Profile}>('/profile','PATCH',data);setProfile(p);notify('Profile updated')}
 const rank=rankFor(profile?.xp||0),nextRank=ranks.find(r=>r.xp>(profile?.xp||0));
 const daily=puzzles.length?puzzles[Math.floor(Date.now()/86400000)%puzzles.length]:null;
 return <div className="app-shell"><header className="app-header"><button className="brand" onClick={()=>{if(game){notify('Use Back to leave your match');return}setTab('play')}} aria-label="NimChess home"><img src="/favicon.svg" alt=""/><span>NimChess<span className="brand-dot">.</span></span></button><div className="header-actions"><button className={'wallet-pill '+(profile?.walletAddress?'connected':'')} onClick={()=>setModal('wallet')}><Wallet size={17}/><span>{profile?.walletAddress?'Connected':'Connect'}</span></button><button className="avatar-button" onClick={()=>{if(!game)setTab('profile')}} aria-label="Your profile"><Avatar name={profile?.avatar}/></button></div></header>
 {error&&<div role="alert" className="error-banner">{error}<button onClick={()=>{setError('');refresh().catch(e=>setError(e.message))}}>Retry</button></div>}
 <main className={game?'main-content in-game':'main-content'}>
 {game?<><MatchView mode={game.mode} match={game.match} difficulty={game.difficulty} minutes={game.minutes} increment={game.increment} playerId={profile?.id} onExit={exitGame} onFinished={savePractice} onMatchChange={m=>{historyReplace(m.id);setGame(g=>g?{...g,match:m}:g)}}/>{game.match?.status==='finished'&&(()=>{const opponent=game.match.white.id===profile?.id?game.match.black:game.match.white;return opponent?.walletAddress?<button className="applause-button" onClick={()=>setTipTarget({name:opponent.name,address:opponent.walletAddress!})}><Heart size={18}/>Good game? Send {opponent.name} some NIM</button>:null})()}</>:<>
 {tab==='play'&&<><section className="welcome"><div><p className="greeting">Hey, {profile?.name||'chess friend'} <span className="wave">✦</span></p><h1>Your move<span>.</span></h1></div><button className="rank-chip" onClick={()=>setTab('profile')}><Zap size={16}/>{rank.name}<ChevronRight size={14}/></button></section><div className="home-grid"><section className="hero-card"><img className="hero-art" src="/assets/knight-club.png" alt="A golden knight and ivory chess pieces on a sculpted board"/><div className="hero-copy"><span className="tiny-tag"><span/> A LITTLE PLAY. A GREAT DAY.</span><h2>Big knight<br/>energy.</h2><p>Find your rhythm.<br/>Make your next great move.</p><button className="primary" onClick={()=>{setSetup('bot');setModal('setup')}}>Let’s play <ArrowRight size={19}/></button></div><span className="hero-footer"><ShieldCheck size={14}/>Free to play. Always your move.</span></section><section className="play-choices"><div className="section-title"><h2>Pick your game</h2><span>Make it yours</span></div><button className="mode-card" onClick={()=>{setSetup('online');setModal('setup')}}><span className="mode-icon yellow"><Swords/></span><span><strong>Challenge a friend</strong><small>Send a link. Settle it on the board.</small></span><ArrowUpRight/></button><button className="mode-card" onClick={()=>{setSetup('bot');setModal('setup')}}><span className="mode-icon green"><Gamepad2/></span><span><strong>Meet your match</strong><small>Three bots. Your kind of challenge.</small></span><ChevronRight/></button><button className="mode-card" onClick={()=>{setSetup('local');setModal('setup')}}><span className="mode-icon peach"><Users/></span><span><strong>Pass & play</strong><small>One phone. Two rivals.</small></span><ChevronRight/></button></section><section className="daily-card"><div className="daily-top"><span className="tiny-tag"><Target size={14}/> THE DAILY MOVE</span><span className="streak"><Flame size={15}/>{profile?.streak||0} day streak</span></div><div className="daily-content"><div><h2>{daily?.title||'A fresh perspective.'}</h2><p>One position. One bright idea.<br/>Your daily dose of “aha”.</p><button className="text-button" disabled={!daily} onClick={()=>{setActivePuzzle(daily);setTab('puzzles')}}>Solve today’s puzzle <ArrowRight size={17}/></button></div><div className="puzzle-emblem"><Lightbulb size={42}/><span>+25 XP</span></div></div></section><section className="fact-card"><div className="fact-icon"><Sparkles/></div><div><small>A LITTLE CHESS WISDOM</small><h3>{facts[fact].title}</h3><p>{facts[fact].text}</p></div><button className="icon-button" aria-label="Another fun fact" onClick={()=>setFact((fact+1)%facts.length)}><Shuffle size={18}/></button></section></div></>}
 {tab==='puzzles'&&<><PageTitle title="Find your spark." subtitle="A little focus. A satisfying finish." icon={<Target/>}/>{activePuzzle?<PuzzlePlay puzzle={activePuzzle} onBack={()=>setActivePuzzle(null)} onSolved={()=>refresh().catch(()=>{})} notify={notify}/>:<><div className="puzzle-stats"><span><Flame/><strong>{profile?.streak||0}</strong>day streak</span><span><Target/><strong>{profile?.puzzlesSolved||0}</strong>solved</span><span><Zap/><strong>{profile?.xp||0}</strong>XP</span></div><div className="section-title"><h2>Your puzzle collection</h2><span>Find the finish</span></div><div className="puzzle-grid">{puzzles.map((p,i)=><button className="puzzle-card" key={p.id} onClick={()=>setActivePuzzle(p)}><div className="puzzle-number">{String(i+1).padStart(2,'0')}<ArrowUpRight size={20}/></div><span className="badge">{p.difficulty}</span><h3>{p.title}</h3><p>{p.theme}</p><span className="text-button">Take a look <ArrowRight size={16}/></span></button>)}</div>{!puzzles.length&&<Empty title="Puzzles are taking a moment" text="Check your connection and reload to fetch the collection."/>}</>}</>}
 {tab==='club'&&<><PageTitle title="Good company." subtitle="Familiar rivals. Friendly competition." icon={<Users/>}/><section className="club-banner"><div><span className="tiny-tag">THE NIMCHESS CLUB</span><h2>A little rivalry.<br/>A lot of respect.</h2><p>Invite someone in. Play a real match.<br/>Let your chess do the talking.</p><button className="primary" onClick={()=>{setSetup('online');setModal('setup')}}><Plus size={18}/>Create a challenge</button></div><Crown className="club-crown"/></section><div className="section-title"><h2>Club standings</h2><span><Trophy size={15}/>Match rating</span></div><p className="subtle">Ratings come from completed eligible friend matches. XP tracks puzzle progress separately.</p><div className="leaderboard">{leaders.length?leaders.map((p,i)=><div className={'leader-row '+(p.id===profile?.id?'is-you':'')} key={p.id}><span className="place">{i+1}</span><Avatar name={p.avatar}/><div className="leader-name"><strong>{p.name}{p.id===profile?.id&&<small> YOU</small>}</strong><span>{rankFor(p.xp).name} · {p.games} games</span></div><strong className="rating">{p.rating}</strong>{p.walletAddress&&p.id!==profile?.id&&<button className="icon-button" aria-label={'Tip '+p.name} onClick={()=>setTipTarget({name:p.name,address:p.walletAddress!})}><Heart size={18}/></button>}</div>):<Empty title="The first seats are yours." text="Complete a friend match to start building the club standings."/>}</div><section className="fair-play"><ShieldCheck/><div><h3>Keep it human.</h3><p>Play your own moves. No outside engines during friend matches. Ratings are for friendly competition; there are no cash stakes.</p></div></section></>}
 {tab==='profile'&&<><div className="section-title profile-title"><h1>Your corner.</h1><button className="icon-button" aria-label="Settings" onClick={()=>setModal('settings')}><Settings/></button></div><section className="profile-card"><div className="profile-cover"><span/><span/><span/></div><Avatar name={profile?.avatar} size="large"/><div className="profile-info"><h2>{profile?.name||'Your player'}</h2><span className="rank-chip"><Zap size={15}/>{rank.name}</span><p>{profile?.bio||'Every great game starts with one move.'}</p><button className="secondary" onClick={()=>setModal('settings')}>Edit profile <User size={16}/></button></div></section><div className="profile-numbers"><div><strong>{profile?.rating||1200}</strong><small>Match rating</small></div><div><strong>{profile?.games||0}</strong><small>Games played</small></div><div><strong>{profile?.wins||0}</strong><small>Wins</small></div></div><section className="progress-card"><div className="section-title"><h2><Zap size={20}/>Your NimRank</h2><strong>{profile?.xp||0} XP</strong></div><div className="progress-track"><span style={{width:Math.min(100,((profile?.xp||0)/(nextRank?.xp||900))*100)+'%'}}/></div><p>{nextRank?`${nextRank.xp-(profile?.xp||0)} XP to ${nextRank.name}. Solve puzzles to move up.`:'Supernova unlocked. Keep the spark alive.'}</p><div className="rank-steps">{ranks.map(r=><span className={(profile?.xp||0)>=r.xp?'unlocked':''} key={r.name}><Sparkles size={18}/>{r.name}</span>)}</div></section><div className="section-title"><h2>Recently played</h2><span>{history.length} matches</span></div><div className="history-list">{history.length?history.map(m=><button className="history-row" key={m.id} onClick={()=>setReplay(m)}><span className="history-icon"><Swords size={20}/></span><span><strong>{m.white.name} vs {m.black?.name||'Opponent'}</strong><small>{new Date(m.createdAt).toLocaleDateString()} · {m.reason||m.status}</small></span><b>{m.result||'—'}</b><ChevronRight size={16}/></button>):<Empty title="Your story starts on the board." text="Play a game and come back to revisit your moves."/>}</div><button className="help-row" onClick={()=>setModal('help')}><BookOpen size={18}/>How to play & club guide<ChevronRight size={18}/></button></>}
 </>}
 </main>
 {!game&&<nav className="bottom-nav" aria-label="Main navigation">{([{id:'play',label:'Play',Icon:Gamepad2},{id:'puzzles',label:'Puzzles',Icon:Target},{id:'club',label:'Club',Icon:Users},{id:'profile',label:'You',Icon:User}] as const).map(({id,label,Icon})=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}><Icon size={22}/><span>{label}</span>{tab===id&&<i/>}</button>)}</nav>}
 {toast&&<div className="toast" role="status" popover="manual" ref={el=>{if(el&&!el.matches(':popover-open'))el.showPopover()}}><span>{toast}</span><button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={17}/></button></div>}
 {modal==='setup'&&<Modal title={setup==='online'?'A friendly showdown':setup==='local'?'Across the same table':'Meet your match'} onClose={()=>setModal(null)}><p className="subtle">{setup==='online'?'Create a private game and share the link with a friend.':setup==='local'?'Take turns on this phone. White makes the first move.':'Choose your pace and your opponent.'}</p>{setup==='bot'&&<><label className="field-label">Your opponent</label><div className="bot-options">{([{id:'easy',name:'Pip',desc:'Finding your feet',avatar:'spark'},{id:'medium',name:'Rooki',desc:'A worthy challenge',avatar:'knight'},{id:'hard',name:'Nova',desc:'Think a move ahead',avatar:'nova'}] as const).map(b=><button className={difficulty===b.id?'selected':''} key={b.id} onClick={()=>setDifficulty(b.id)}><Avatar name={b.avatar}/><strong>{b.name}</strong><small>{b.desc}</small></button>)}</div></>}<label className="field-label">Time per player</label><div className="segmented">{[3,5,10].map(n=><button className={minutes===n?'selected':''} key={n} onClick={()=>setMinutes(n)}><Clock size={16}/>{n} min</button>)}</div><label className="field-label">Extra seconds after each move</label><div className="segmented">{[0,2,5].map(n=><button className={increment===n?'selected':''} key={n} onClick={()=>setIncrement(n)}>+{n} sec</button>)}</div><button className="primary full" disabled={busy||!profile} onClick={start}>{busy?<LoaderCircle className="spin"/>:<Play size={18}/>} {setup==='online'?'Create challenge':'Start game'}</button><p className="micro">{setup==='online'?'Private friend matches. No entry fee.':'Practice games never affect your club rating.'}</p></Modal>}
 {modal==='settings'&&profile&&<SettingsDialog profile={profile} onSave={saveProfile} onClose={()=>setModal(null)} notify={notify}/>}
 {modal==='wallet'&&<WalletDialog profile={profile} refresh={refresh} notify={notify} onClose={()=>setModal(null)}/>}
 {tipTarget&&<TipDialog target={tipTarget} notify={notify} onClose={()=>setTipTarget(null)}/>}
 {modal==='help'&&<Modal title="Make yourself at home." onClose={()=>setModal(null)}><div className="guide"><h3>The goal</h3><p>Checkmate your opponent: attack their king so they cannot escape. White moves first, then players alternate.</p><h3>Making a move</h3><p>Tap a piece to see its legal moves, then tap a destination. Pawns promote on the far rank. The board handles castling, en passant, and checks.</p><h3>Your kind of game</h3><p>Practice with Pip, Rooki, or Nova. Pass the phone for a local game. Or create a friend challenge and share its link.</p><h3>Ranks & puzzles</h3><p>Complete puzzles to earn XP and unlock NimRanks. Your match rating is separate, based on eligible games against other players.</p><h3>A little appreciation</h3><p>Connect through Nimiq Pay to enable optional NIM tips. Review the address, amount, and network in your wallet before confirming.</p></div></Modal>}
 {replay&&<ReplayDialog match={replay} onClose={()=>setReplay(null)}/>}
 </div>
}
function PageTitle({title,subtitle,icon}:{title:string;subtitle:string;icon:React.ReactNode}){return <section className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div><span>{icon}</span></section>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><Sparkles size={27}/><h3>{title}</h3><p>{text}</p></div>}
function SettingsDialog({profile,onSave,onClose,notify}:{profile:Profile;onSave:(p:Partial<Profile>)=>Promise<void>;onClose:()=>void;notify:(s:string)=>void}){const [name,setName]=useState(profile.name),[bio,setBio]=useState(profile.bio),[avatar,setAvatar]=useState(profile.avatar),[theme,setTheme]=useState(profile.theme||'sage'),[busy,setBusy]=useState(false);return <Modal title="Make it yours." onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await onSave({name,bio,avatar,theme});onClose()}catch(e){notify((e as Error).message)}finally{setBusy(false)}}}><label className="field-label" htmlFor="player-name">Player name</label><input id="player-name" value={name} minLength={2} maxLength={24} required onChange={e=>setName(e.target.value)}/><label className="field-label" htmlFor="player-bio">A little about you</label><textarea id="player-bio" value={bio} maxLength={160} rows={3} onChange={e=>setBio(e.target.value)}/><label className="field-label">Choose your character</label><div className="avatar-options">{avatars.map(a=><button type="button" className={avatar===a?'selected':''} aria-label={a+' avatar'} aria-pressed={avatar===a} key={a} onClick={()=>setAvatar(a)}><Avatar name={a}/></button>)}</div><label className="field-label">Board palette</label><div className="segmented">{['sage','midnight','sand'].map(t=><button type="button" key={t} className={theme===t?'selected':''} onClick={()=>setTheme(t)}><Palette size={16}/>{t}</button>)}</div><button disabled={busy} className="primary full" type="submit">{busy?'Saving…':'Save profile'}<Check size={17}/></button><p className="micro">Your guest profile is saved on this browser. Wallet linking does not yet move progress between devices.</p></form></Modal>}
function PuzzlePlay({puzzle,onBack,onSolved,notify}:{puzzle:Puzzle;onBack:()=>void;onSolved:()=>void;notify:(s:string)=>void}){const [fen,setFen]=useState(puzzle.fen),[moves,setMoves]=useState<string[]>([]),[state,setState]=useState<'playing'|'solved'|'revealed'>('playing'),[hint,setHint]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);function reset(){setFen(puzzle.fen);setMoves([]);setState('playing');setHint(false);setMessage('')};async function move(m:{from:string;to:string;promotion?:string}){if(state!=='playing'||busy)return;const chess=new Chess(fen);try{const played=chess.move(m);const expected=puzzle.solution[moves.length];const uci=played.from+played.to+(played.promotion||'');if(uci!==expected&&played.san!==expected){setMessage('Almost. Look for a more forcing move.');return}let next=[...moves,expected];if(next.length<puzzle.solution.length){chess.move(puzzle.solution[next.length]);next=[...next,puzzle.solution[next.length]]}setFen(chess.fen());setMoves(next);setMessage('Good find. Keep going.');if(next.length===puzzle.solution.length){setBusy(true);try{await api('/puzzles/'+puzzle.id+'/solve','POST',{moves:next});setState('solved');setMessage('Beautifully played.');onSolved()}catch(e){notify((e as Error).message);setMoves([]);setFen(puzzle.fen);setMessage('Could not save your solve. Please try again.')}finally{setBusy(false)}}}catch{setMessage('Try a legal move with the highlighted piece.')}}return <section className="puzzle-play"><button className="text-button" onClick={onBack}>← Puzzle collection</button><div className="section-title"><h2>{puzzle.title}</h2><span className="badge">{puzzle.difficulty}</span></div><p>{new Chess(puzzle.fen).turn()==='w'?'White':'Black'} to move · {puzzle.theme}</p><ChessBoard fen={fen} onMove={move} orientation={new Chess(puzzle.fen).turn()} disabled={state!=='playing'||busy}/><p className={'puzzle-feedback '+(state==='solved'?'success':'')} role="status">{message||'Take your time. Find the best move.'}</p>{hint&&<p className="hint"><Lightbulb size={17}/>Look at {puzzle.solution[moves.length]?.slice(0,2)}. {puzzle.theme}.</p>}{state==='playing'?<div className="button-row"><button className="secondary" onClick={()=>setHint(true)}><Lightbulb size={17}/>Hint</button><button className="secondary" onClick={()=>{const c=new Chess(puzzle.fen);puzzle.solution.forEach(m=>c.move(m));setFen(c.fen());setState('revealed');setMessage('Solution: '+puzzle.solution.join(' → '))}}>Show solution</button></div>:<div className="solution-box"><h3>{state==='solved'?'A spark of brilliance.':'Now you see it.'}</h3><p>{puzzle.explanation}</p><button className="primary" onClick={reset}>Try again<ArrowRight size={18}/></button></div>}</section>}
function ReplayDialog({match,onClose}:{match:Match;onClose:()=>void}){const c=new Chess();try{c.loadPgn(match.pgn)}catch{}const moves=c.history();const [step,setStep]=useState(moves.length);const board=new Chess();moves.slice(0,step).forEach(m=>board.move(m));return <Modal title="Every move tells a story." onClose={onClose}><p>{match.white.name} vs {match.black?.name||'Opponent'} · {match.result}</p><ChessBoard fen={board.fen()} disabled/><input aria-label="Replay move" type="range" min={0} max={moves.length} value={step} onChange={e=>setStep(Number(e.target.value))}/><div className="button-row"><button className="secondary" disabled={step===0} onClick={()=>setStep(step-1)}>← Previous</button><span>{step} / {moves.length}</span><button className="secondary" disabled={step===moves.length} onClick={()=>setStep(step+1)}>Next →</button></div><p className="move-log">{moves.slice(0,step).join(' ')||'Starting position'}</p><button className="secondary full" onClick={()=>download(match.pgn,`nimchess-${match.id}.pgn`)}><Download size={17}/>Download PGN</button></Modal>}
function WalletDialog({profile,refresh,notify,onClose}:{profile:Profile|null;refresh:()=>Promise<Profile>;notify:(s:string)=>void;onClose:()=>void}){const [busy,setBusy]=useState(false);return <Modal title="Your NIM connection." onClose={onClose}><div className="wallet-illustration"><Wallet size={38}/><Sparkles size={22}/></div><h3>{profile?.walletAddress?'You’re connected.':'A little NIM. A little kindness.'}</h3><p className="subtle">Connect inside Nimiq Pay to add a verified tipping address to your player profile.</p>{profile?.walletAddress?<><div className="address-box">{profile.walletAddress}</div><p className="micro">Tips go directly to the other player. NimChess does not hold funds.</p><button className="secondary full" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/wallet','DELETE');const w=await import('./wallet');w.disconnectWallet();await refresh();notify('Wallet disconnected')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}}>Disconnect wallet</button></>:<button className="primary full" disabled={busy||!profile} onClick={async()=>{setBusy(true);try{const {challenge}=await api<{challenge:string}>('/wallet/challenge','POST');const w=await import('./wallet');const signed=await w.connectWallet(challenge);await api('/wallet','POST',{...signed,challenge});await refresh();notify('Wallet connected')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}}>{busy?<LoaderCircle className="spin"/>:<Wallet size={18}/>} {busy?'Check Nimiq Pay…':'Connect Nimiq Pay'}</button>}<p className="micro">Approve only the connection you requested. You can play without connecting.</p></Modal>}
function TipDialog({target,onClose,notify}:{target:{name:string;address:string};onClose:()=>void;notify:(s:string)=>void}){const [amount,setAmount]=useState('1'),[busy,setBusy]=useState(false),[hash,setHash]=useState('');return <Modal title={'A little applause for '+target.name} onClose={()=>{if(!busy)onClose()}}><p className="subtle">Send an optional NIM tip directly to this player.</p><div className="address-box">{target.address}</div><label className="field-label" htmlFor="tip-amount">Amount in NIM</label><input id="tip-amount" type="number" min="0.00001" max="100" step="0.00001" value={amount} onChange={e=>setAmount(e.target.value)}/><p className="micro">Check the active network, recipient, and any fee in Nimiq Pay before approving. Your wallet’s current network will be used.</p>{hash?<div className="success-box"><Check/><strong>Transaction submitted</strong><p>Check Nimiq Pay for confirmation.</p><code>{hash}</code></div>:<button className="primary full" disabled={busy||!(Number(amount)>0)||Number(amount)>100} onClick={async()=>{setBusy(true);try{const w=await import('./wallet');setHash(await w.sendTip(target.address,Number(amount)));notify('Tip submitted to the network')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}}>{busy?<LoaderCircle className="spin"/>:<Heart size={18}/>} {busy?'Check your wallet…':'Review tip in Nimiq Pay'}</button>}</Modal>}
